### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by Nooby-001** [JamesLemony/obsidian_vibrant#2]
Hi, I don't know what Discord is so I'll leave this here.
Your theme's great for night time but the letters are too bright and contrast too much with the dark background, I suggest a "glow" behind the letters like the 80s Neon theme has (had?) and a "cards layout style" like the Anuppuccin and Shiba Uni themes.
Thanks!

Screenshots:
https://imgur.com/a/5g3su5x

**Comment by JamesLemony** [comment]
Hi! Thank you very much for reaching out to me. I, too, agree that white letters and black background is too eye-piercing for my eyes. I'll try the glow effect in a few days, hopefully, and will get back to you. But to be honest, I do not want glow in the theme at the moment because I think it will not fit with the rest of the theme. We will see!
Thanks for your valuable feedback!

**Comment by JamesLemony** [comment]
Hi! I have changed the background color from black to a shade of gray. I think this is better for the eyes. I have tried the glowing effect but it just wasn't for me. I would love a feedback from you.

**Comment by Nooby-001** [comment]
It's easier on the eyes, thank you!
